//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18047
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svr.Plugin.Host.WSSyncToSAP {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSSyncToSAP.SAPSyncServiceSoap")]
    public interface SAPSyncServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNormalToSyncMADCCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetNormalToSyncMADCCode(string cBusinessTypeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNormalSyncErrorMADCCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetNormalSyncErrorMADCCode(string cBusinessTypeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNormalSyncErrorWInOutInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetNormalSyncErrorWInOutInfo(string cBusinessTypeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncNormalWInOutInfoToSyncToSAP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SyncNormalWInOutInfoToSyncToSAP(out string cSyncMessage, string cMADCCode, string cBusinessTypeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncNormalWInOutInfoSyncErrorToSAP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SyncNormalWInOutInfoSyncErrorToSAP(out string cSyncMessage, string cMADCCode, string cBusinessTypeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncNormalWInOutInfoToSAPByBarCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SyncNormalWInOutInfoToSAPByBarCode(out string cSyncMessage, string cBikeBarcodeList, string cBusinessTypeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBackToSyncMADCCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetBackToSyncMADCCode(string cBusinessTypeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBackSyncErrorMADCCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetBackSyncErrorMADCCode(string cBusinessTypeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBackSyncErrorWInOutInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetBackSyncErrorWInOutInfo(string cBusinessTypeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncBackWInOutInfoToSyncToSAP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SyncBackWInOutInfoToSyncToSAP(out string cSyncMessage, string cMADCCode, string cBusinessTypeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncBackWInOutInfoSyncErrorToSAP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SyncBackWInOutInfoSyncErrorToSAP(out string cSyncMessage, string cMADCCode, string cBusinessTypeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncBackWInOutInfoToSAPByBarCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SyncBackWInOutInfoToSAPByBarCode(out string cSyncMessage, string cBikeBarcodeList, string cBusinessTypeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProduceNormalToSyncOrderCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetProduceNormalToSyncOrderCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProduceNormalSyncErrorOrderCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetProduceNormalSyncErrorOrderCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProduceNormalSyncErrorThreeBarCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetProduceNormalSyncErrorThreeBarCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncProduceNormalThreeBarcodeToSyncToSAP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SyncProduceNormalThreeBarcodeToSyncToSAP(out string cSyncMessage, string cOrderCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncProduceNormalThreeBarcodeSyncErrorToSAP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SyncProduceNormalThreeBarcodeSyncErrorToSAP(out string cSyncMessage, string cOrderCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncProduceNormalThreeBarCodeToSAPByBarCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SyncProduceNormalThreeBarCodeToSAPByBarCode(out string cSyncMessage, string cBikeBarcodeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProduceRebindToSyncOrderCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetProduceRebindToSyncOrderCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProduceRebindSyncErrorOrderCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetProduceRebindSyncErrorOrderCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProduceSyncErrorReBindThreeBarcode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetProduceSyncErrorReBindThreeBarcode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncProduceReBindThreeBarcodeToSyncToSAP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SyncProduceReBindThreeBarcodeToSyncToSAP(out string cSyncMessage, string cOrderCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncProduceReBindThreeBarcodeSyncErrorToSAP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SyncProduceReBindThreeBarcodeSyncErrorToSAP(out string cSyncMessage, string cOrderCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncProduceReBindThreeBarcodeToSAPByBarCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SyncProduceReBindThreeBarcodeToSAPByBarCode(out string cSyncMessage, string cBikeBarcodeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPurchaseNormalToSyncOrderCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPurchaseNormalToSyncOrderCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPurchaseNormalSyncErrorOrderCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPurchaseNormalSyncErrorOrderCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPurchaseNormalSyncErrorThreeBarCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPurchaseNormalSyncErrorThreeBarCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncPurchaseNormalThreeBarcodeToSyncToSAP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SyncPurchaseNormalThreeBarcodeToSyncToSAP(out string cSyncMessage, string cOrderCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncPurchaseNormalThreeBarcodeSyncErrorToSAP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SyncPurchaseNormalThreeBarcodeSyncErrorToSAP(out string cSyncMessage, string cOrderCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncPurchaseNormalThreeBarCodeToSAPByBarCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SyncPurchaseNormalThreeBarCodeToSAPByBarCode(out string cSyncMessage, string cBikeBarcodeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPurchaseRebindToSyncOrderCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPurchaseRebindToSyncOrderCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPurchaseRebindSyncErrorOrderCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPurchaseRebindSyncErrorOrderCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPurchaseSyncErrorReBindThreeBarcode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPurchaseSyncErrorReBindThreeBarcode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncPurchaseReBindThreeBarcodeToSyncToSAP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SyncPurchaseReBindThreeBarcodeToSyncToSAP(out string cSyncMessage, string cOrderCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncPurchaseReBindThreeBarcodeSyncErrorToSAP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SyncPurchaseReBindThreeBarcodeSyncErrorToSAP(out string cSyncMessage, string cOrderCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncPurchaseReBindThreeBarcodeToSAPByBarCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SyncPurchaseReBindThreeBarcodeToSAPByBarCode(out string cSyncMessage, string cBikeBarcodeList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SAPSyncServiceSoapChannel : Svr.Plugin.Host.WSSyncToSAP.SAPSyncServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SAPSyncServiceSoapClient : System.ServiceModel.ClientBase<Svr.Plugin.Host.WSSyncToSAP.SAPSyncServiceSoap>, Svr.Plugin.Host.WSSyncToSAP.SAPSyncServiceSoap {
        
        public SAPSyncServiceSoapClient() {
        }
        
        public SAPSyncServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SAPSyncServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAPSyncServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAPSyncServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetNormalToSyncMADCCode(string cBusinessTypeList) {
            return base.Channel.GetNormalToSyncMADCCode(cBusinessTypeList);
        }
        
        public System.Data.DataTable GetNormalSyncErrorMADCCode(string cBusinessTypeList) {
            return base.Channel.GetNormalSyncErrorMADCCode(cBusinessTypeList);
        }
        
        public System.Data.DataTable GetNormalSyncErrorWInOutInfo(string cBusinessTypeList) {
            return base.Channel.GetNormalSyncErrorWInOutInfo(cBusinessTypeList);
        }
        
        public bool SyncNormalWInOutInfoToSyncToSAP(out string cSyncMessage, string cMADCCode, string cBusinessTypeList) {
            return base.Channel.SyncNormalWInOutInfoToSyncToSAP(out cSyncMessage, cMADCCode, cBusinessTypeList);
        }
        
        public bool SyncNormalWInOutInfoSyncErrorToSAP(out string cSyncMessage, string cMADCCode, string cBusinessTypeList) {
            return base.Channel.SyncNormalWInOutInfoSyncErrorToSAP(out cSyncMessage, cMADCCode, cBusinessTypeList);
        }
        
        public bool SyncNormalWInOutInfoToSAPByBarCode(out string cSyncMessage, string cBikeBarcodeList, string cBusinessTypeList) {
            return base.Channel.SyncNormalWInOutInfoToSAPByBarCode(out cSyncMessage, cBikeBarcodeList, cBusinessTypeList);
        }
        
        public System.Data.DataTable GetBackToSyncMADCCode(string cBusinessTypeList) {
            return base.Channel.GetBackToSyncMADCCode(cBusinessTypeList);
        }
        
        public System.Data.DataTable GetBackSyncErrorMADCCode(string cBusinessTypeList) {
            return base.Channel.GetBackSyncErrorMADCCode(cBusinessTypeList);
        }
        
        public System.Data.DataTable GetBackSyncErrorWInOutInfo(string cBusinessTypeList) {
            return base.Channel.GetBackSyncErrorWInOutInfo(cBusinessTypeList);
        }
        
        public bool SyncBackWInOutInfoToSyncToSAP(out string cSyncMessage, string cMADCCode, string cBusinessTypeList) {
            return base.Channel.SyncBackWInOutInfoToSyncToSAP(out cSyncMessage, cMADCCode, cBusinessTypeList);
        }
        
        public bool SyncBackWInOutInfoSyncErrorToSAP(out string cSyncMessage, string cMADCCode, string cBusinessTypeList) {
            return base.Channel.SyncBackWInOutInfoSyncErrorToSAP(out cSyncMessage, cMADCCode, cBusinessTypeList);
        }
        
        public bool SyncBackWInOutInfoToSAPByBarCode(out string cSyncMessage, string cBikeBarcodeList, string cBusinessTypeList) {
            return base.Channel.SyncBackWInOutInfoToSAPByBarCode(out cSyncMessage, cBikeBarcodeList, cBusinessTypeList);
        }
        
        public System.Data.DataTable GetProduceNormalToSyncOrderCode() {
            return base.Channel.GetProduceNormalToSyncOrderCode();
        }
        
        public System.Data.DataTable GetProduceNormalSyncErrorOrderCode() {
            return base.Channel.GetProduceNormalSyncErrorOrderCode();
        }
        
        public System.Data.DataTable GetProduceNormalSyncErrorThreeBarCode() {
            return base.Channel.GetProduceNormalSyncErrorThreeBarCode();
        }
        
        public bool SyncProduceNormalThreeBarcodeToSyncToSAP(out string cSyncMessage, string cOrderCode) {
            return base.Channel.SyncProduceNormalThreeBarcodeToSyncToSAP(out cSyncMessage, cOrderCode);
        }
        
        public bool SyncProduceNormalThreeBarcodeSyncErrorToSAP(out string cSyncMessage, string cOrderCode) {
            return base.Channel.SyncProduceNormalThreeBarcodeSyncErrorToSAP(out cSyncMessage, cOrderCode);
        }
        
        public bool SyncProduceNormalThreeBarCodeToSAPByBarCode(out string cSyncMessage, string cBikeBarcodeList) {
            return base.Channel.SyncProduceNormalThreeBarCodeToSAPByBarCode(out cSyncMessage, cBikeBarcodeList);
        }
        
        public System.Data.DataTable GetProduceRebindToSyncOrderCode() {
            return base.Channel.GetProduceRebindToSyncOrderCode();
        }
        
        public System.Data.DataTable GetProduceRebindSyncErrorOrderCode() {
            return base.Channel.GetProduceRebindSyncErrorOrderCode();
        }
        
        public System.Data.DataTable GetProduceSyncErrorReBindThreeBarcode() {
            return base.Channel.GetProduceSyncErrorReBindThreeBarcode();
        }
        
        public bool SyncProduceReBindThreeBarcodeToSyncToSAP(out string cSyncMessage, string cOrderCode) {
            return base.Channel.SyncProduceReBindThreeBarcodeToSyncToSAP(out cSyncMessage, cOrderCode);
        }
        
        public bool SyncProduceReBindThreeBarcodeSyncErrorToSAP(out string cSyncMessage, string cOrderCode) {
            return base.Channel.SyncProduceReBindThreeBarcodeSyncErrorToSAP(out cSyncMessage, cOrderCode);
        }
        
        public bool SyncProduceReBindThreeBarcodeToSAPByBarCode(out string cSyncMessage, string cBikeBarcodeList) {
            return base.Channel.SyncProduceReBindThreeBarcodeToSAPByBarCode(out cSyncMessage, cBikeBarcodeList);
        }
        
        public System.Data.DataTable GetPurchaseNormalToSyncOrderCode() {
            return base.Channel.GetPurchaseNormalToSyncOrderCode();
        }
        
        public System.Data.DataTable GetPurchaseNormalSyncErrorOrderCode() {
            return base.Channel.GetPurchaseNormalSyncErrorOrderCode();
        }
        
        public System.Data.DataTable GetPurchaseNormalSyncErrorThreeBarCode() {
            return base.Channel.GetPurchaseNormalSyncErrorThreeBarCode();
        }
        
        public bool SyncPurchaseNormalThreeBarcodeToSyncToSAP(out string cSyncMessage, string cOrderCode) {
            return base.Channel.SyncPurchaseNormalThreeBarcodeToSyncToSAP(out cSyncMessage, cOrderCode);
        }
        
        public bool SyncPurchaseNormalThreeBarcodeSyncErrorToSAP(out string cSyncMessage, string cOrderCode) {
            return base.Channel.SyncPurchaseNormalThreeBarcodeSyncErrorToSAP(out cSyncMessage, cOrderCode);
        }
        
        public bool SyncPurchaseNormalThreeBarCodeToSAPByBarCode(out string cSyncMessage, string cBikeBarcodeList) {
            return base.Channel.SyncPurchaseNormalThreeBarCodeToSAPByBarCode(out cSyncMessage, cBikeBarcodeList);
        }
        
        public System.Data.DataTable GetPurchaseRebindToSyncOrderCode() {
            return base.Channel.GetPurchaseRebindToSyncOrderCode();
        }
        
        public System.Data.DataTable GetPurchaseRebindSyncErrorOrderCode() {
            return base.Channel.GetPurchaseRebindSyncErrorOrderCode();
        }
        
        public System.Data.DataTable GetPurchaseSyncErrorReBindThreeBarcode() {
            return base.Channel.GetPurchaseSyncErrorReBindThreeBarcode();
        }
        
        public bool SyncPurchaseReBindThreeBarcodeToSyncToSAP(out string cSyncMessage, string cOrderCode) {
            return base.Channel.SyncPurchaseReBindThreeBarcodeToSyncToSAP(out cSyncMessage, cOrderCode);
        }
        
        public bool SyncPurchaseReBindThreeBarcodeSyncErrorToSAP(out string cSyncMessage, string cOrderCode) {
            return base.Channel.SyncPurchaseReBindThreeBarcodeSyncErrorToSAP(out cSyncMessage, cOrderCode);
        }
        
        public bool SyncPurchaseReBindThreeBarcodeToSAPByBarCode(out string cSyncMessage, string cBikeBarcodeList) {
            return base.Channel.SyncPurchaseReBindThreeBarcodeToSAPByBarCode(out cSyncMessage, cBikeBarcodeList);
        }
    }
}
